# Generated by Django 5.0.1 on 2024-01-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='event name')),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('venue', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('descrpition', models.TextField(blank=True)),
            ],
        ),
    ]
